export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const IS_LOGGED_IN_SUCESS = "IS_LOGGED_IN_SUCCESS";
export const IS_LOGGED_IN_FAILURE = "IS_LOGGED_IN_FAILURE"; 

export const CREATE_USER_IN_DB = 'CREATE_USER_IN_DB';
export const CREATE_USER_IN_DB_SUCCESS = 'CREATE_USER_IN_DB_SUCCESS';
export const CREATE_USER_IN_DB_FAILURE = 'CREATE_USER_IN_DB_FAILURE';

export const CREATE_COMPANY = 'CREATE_COMPANY'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE'

export const GET_COMPANIES = 'GET_COMPANIES'
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS'
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE'

export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const SELECTED_COMPANY = 'SELECTED_COMPANY'

//buses

export const CREATE_BUS = 'CREATE_BUS'
export const CREATE_BUS_SUCCESS = 'CREATE_BUS_SUCCESS'
export const CREATE_BUS_FAILURE = 'CREATE_BUS_FAILURE'

export const ADD_CITY = 'ADD_CITY'
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS'
export const ADD_CITY_FAILURE = 'ADD_CITY_FAILURE'

export const GET_CITIES = 'GET_CITIES'
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE'

export const GET_BUSES = 'GET_BUSES'
export const GET_BUSES_SUCCESS = 'GET_BUSES_SUCCESS'
export const GET_BUSES_FAILURE = 'GET_BUSES_FAILURE'