export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const CREATE_USER_IN_DB = 'CREATE_USER_IN_DB';
export const CREATE_USER_IN_DB_SUCCESS = 'CREATE_USER_IN_DB_SUCCESS';
export const CREATE_USER_IN_DB_FAILURE = 'CREATE_USER_IN_DB_FAILURE'